# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import store_pb2 as store__pb2


class StoreStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetQuantity = channel.unary_unary(
        '/store.Store/GetQuantity',
        request_serializer=store__pb2.QuantityRequest.SerializeToString,
        response_deserializer=store__pb2.QuantityResponse.FromString,
        )


class StoreServicer(object):

  def GetQuantity(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetQuantity': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuantity,
          request_deserializer=store__pb2.QuantityRequest.FromString,
          response_serializer=store__pb2.QuantityResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.Store', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
