# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='store.proto',
  package='store',
  syntax='proto3',
  serialized_pb=_b('\n\x0bstore.proto\x12\x05store\"\x17\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"\x15\n\x04\x42ool\x12\r\n\x05value\x18\x01 \x01(\x08\"\"\n\x0fQuantityRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"$\n\x10QuantityResponse\x12\x10\n\x08quantity\x18\x01 \x01(\x05\x32v\n\x05Store\x12@\n\x0bGetQuantity\x12\x16.store.QuantityRequest\x1a\x17.store.QuantityResponse\"\x00\x12+\n\x0bStocksItems\x12\x0b.store.Item\x1a\x0b.store.Bool\"\x00(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='store.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='store.Item.item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='store.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='store.Bool.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=68,
)


_QUANTITYREQUEST = _descriptor.Descriptor(
  name='QuantityRequest',
  full_name='store.QuantityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='store.QuantityRequest.item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=104,
)


_QUANTITYRESPONSE = _descriptor.Descriptor(
  name='QuantityResponse',
  full_name='store.QuantityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='store.QuantityResponse.quantity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['QuantityRequest'] = _QUANTITYREQUEST
DESCRIPTOR.message_types_by_name['QuantityResponse'] = _QUANTITYRESPONSE

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.Item)
  ))
_sym_db.RegisterMessage(Item)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), dict(
  DESCRIPTOR = _BOOL,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.Bool)
  ))
_sym_db.RegisterMessage(Bool)

QuantityRequest = _reflection.GeneratedProtocolMessageType('QuantityRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUANTITYREQUEST,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.QuantityRequest)
  ))
_sym_db.RegisterMessage(QuantityRequest)

QuantityResponse = _reflection.GeneratedProtocolMessageType('QuantityResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUANTITYRESPONSE,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.QuantityResponse)
  ))
_sym_db.RegisterMessage(QuantityResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class StoreStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetQuantity = channel.unary_unary(
          '/store.Store/GetQuantity',
          request_serializer=QuantityRequest.SerializeToString,
          response_deserializer=QuantityResponse.FromString,
          )
      self.StocksItems = channel.stream_unary(
          '/store.Store/StocksItems',
          request_serializer=Item.SerializeToString,
          response_deserializer=Bool.FromString,
          )


  class StoreServicer(object):

    def GetQuantity(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StocksItems(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetQuantity': grpc.unary_unary_rpc_method_handler(
            servicer.GetQuantity,
            request_deserializer=QuantityRequest.FromString,
            response_serializer=QuantityResponse.SerializeToString,
        ),
        'StocksItems': grpc.stream_unary_rpc_method_handler(
            servicer.StocksItems,
            request_deserializer=Item.FromString,
            response_serializer=Bool.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'store.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaStoreServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetQuantity(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StocksItems(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaStoreStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetQuantity(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetQuantity.future = None
    def StocksItems(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    StocksItems.future = None


  def beta_create_Store_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('store.Store', 'GetQuantity'): QuantityRequest.FromString,
      ('store.Store', 'StocksItems'): Item.FromString,
    }
    response_serializers = {
      ('store.Store', 'GetQuantity'): QuantityResponse.SerializeToString,
      ('store.Store', 'StocksItems'): Bool.SerializeToString,
    }
    method_implementations = {
      ('store.Store', 'GetQuantity'): face_utilities.unary_unary_inline(servicer.GetQuantity),
      ('store.Store', 'StocksItems'): face_utilities.stream_unary_inline(servicer.StocksItems),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Store_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('store.Store', 'GetQuantity'): QuantityRequest.SerializeToString,
      ('store.Store', 'StocksItems'): Item.SerializeToString,
    }
    response_deserializers = {
      ('store.Store', 'GetQuantity'): QuantityResponse.FromString,
      ('store.Store', 'StocksItems'): Bool.FromString,
    }
    cardinalities = {
      'GetQuantity': cardinality.Cardinality.UNARY_UNARY,
      'StocksItems': cardinality.Cardinality.STREAM_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'store.Store', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
